//
// DyneTK, the Dyne Toolkit
// Copyright (C) 2007 Matthias Melcher
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
//

// generated by Fast Light User Interface Designer (fluid) version 1.0300

#ifndef Fldtk_Format_Slot_Editor_h
#define Fldtk_Format_Slot_Editor_h
#include <FL/Fl.H>
#include "Fldtk_Value_Slot_Editor.h"
class Dtk_Value_Slot;
#include <FL/Fl_Box.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Choice.H>

class Fldtk_Format_Slot_Editor : public Fldtk_Value_Slot_Editor {
public:
  Fldtk_Format_Slot_Editor(Fl_Group *container, Dtk_Value_Slot *slot) ;
  ~Fldtk_Format_Slot_Editor();
  void value(double v);
  double value();
private:
  int value_; 
  Fl_Group* buildUI_();
public:
  Fl_Input *wPen;
  Fl_Input *wRoundness;
  Fl_Input *wInset;
  Fl_Input *wShadow;
  Fl_Choice *wFrame;
  static Fl_Menu_Item menu_wFrame[];
  Fl_Choice *wFill;
  static Fl_Menu_Item menu_wFill[];
  Fl_Choice *wLines;
  static Fl_Menu_Item menu_wLines[];
};
/** \class Fldtk_Format_Slot_Editor
 * A big editor for a single 32-bit viewFormat value.
 *
 * \fixme "value()" functions are not complete yet.
 */
#endif

//
// DyneTK, the Dyne Toolkit
// Copyright (C) 2007 Matthias Melcher
//
