//
// DyneTK, the Dyne Toolkit
// Copyright (C) 2007 Matthias Melcher
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
//

// generated by Fast Light User Interface Designer (fluid) version 1.0108

#ifndef Fldtk_Justify_Slot_Editor_h
#define Fldtk_Justify_Slot_Editor_h
#include <FL/Fl.H>
#include "Fldtk_Value_Slot_Editor.h"
class Dtk_Value_Slot;
#include <FL/Fl_Group.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Choice.H>
#include <FL/Fl_Check_Button.H>

class Fldtk_Justify_Slot_Editor : public Fldtk_Value_Slot_Editor {
public:
  Fldtk_Justify_Slot_Editor(Fl_Group *container, Dtk_Value_Slot *slot) ;
  ~Fldtk_Justify_Slot_Editor();
  void value(double v);
  double value();
private:
  int value_; 
  Fl_Group* buildUI_();
public:
  Fl_Choice *wHParent;
  static Fl_Menu_Item menu_wHParent[];
  Fl_Choice *wHSibling;
  static Fl_Menu_Item menu_wHSibling[];
  Fl_Choice *wVParent;
  static Fl_Menu_Item menu_wVParent[];
  Fl_Choice *wVSibling;
  static Fl_Menu_Item menu_wVSibling[];
  Fl_Check_Button *wPropLeft;
  Fl_Check_Button *wPropRight;
  Fl_Check_Button *wPropTop;
  Fl_Check_Button *wPropBottom;
  Fl_Choice *wHText;
  static Fl_Menu_Item menu_wHText[];
  Fl_Choice *wVText;
  static Fl_Menu_Item menu_wVText[];
  Fl_Choice *wTextLimits;
  static Fl_Menu_Item menu_wTextLimits[];
  Fl_Check_Button *wReflow;
  Fl_Check_Button *wLasso;
  Fl_Check_Button *wAnchored;
};
#endif

//
// DyneTK, the Dyne Toolkit
// Copyright (C) 2007 Matthias Melcher
//
