//
// DyneTK, the Dyne Toolkit
// Copyright (C) 2007 Matthias Melcher
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
//

// generated by Fast Light User Interface Designer (fluid) version 1.0108

#ifndef Fldtk_Prefs_h
#define Fldtk_Prefs_h
#include <FL/Fl.H>
#include <FL/Fl_Preferences.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Check_Button.H>
#include <FL/Fl_Box.H>

class Fldtk_Prefs_App : public Fl_Group {
public:
  Fldtk_Prefs_App(int X, int Y, int W, int H, const char *L = 0);
};
#include <FL/Fl_Choice.H>
#include <FL/Fl_Input.H>

class Fldtk_Prefs_Layout : public Fl_Group {
public:
  Fldtk_Prefs_Layout(int X, int Y, int W, int H, const char *L = 0);
  static Fl_Menu_Item menu_Size[];
};
#include <FL/Fl_Button.H>

class Fldtk_Prefs_Browser : public Fl_Group {
public:
  Fldtk_Prefs_Browser(int X, int Y, int W, int H, const char *L = 0);
  static Fl_Menu_Item menu_Sort[];
  static Fl_Menu_Item menu_Sort1[];
};

class Fldtk_Prefs_Text : public Fl_Group {
public:
  Fldtk_Prefs_Text(int X, int Y, int W, int H, const char *L = 0);
};

class Fldtk_Prefs_Packages : public Fl_Group {
public:
  Fldtk_Prefs_Packages(int X, int Y, int W, int H, const char *L = 0);
  static Fl_Menu_Item menu_Type[];
  Fl_Choice *wPort;
private:
  void cb_wPort_i(Fl_Choice*, void*);
  static void cb_wPort(Fl_Choice*, void*);
  static Fl_Menu_Item menu_wPort[];
  int port_; 
public:
  int port();
  void get_prefs(Fl_Preferences &prefs);
  void set_prefs(Fl_Preferences &prefs);
  void update_data();
  void update_dialog();
};

class Fldtk_Prefs_Heaps : public Fl_Group {
public:
  Fldtk_Prefs_Heaps(int X, int Y, int W, int H, const char *L = 0);
};
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Tabs.H>

class Fldtk_Prefs : public Fl_Double_Window {
  void _Fldtk_Prefs();
public:
  Fldtk_Prefs(int X, int Y, int W, int H, const char *L = 0);
  Fldtk_Prefs(int W, int H, const char *L = 0);
  Fldtk_Prefs_App *app;
  Fldtk_Prefs_Layout *layout;
  Fldtk_Prefs_Browser *browser;
  Fldtk_Prefs_Text *text;
  Fldtk_Prefs_Packages *packages;
  Fldtk_Prefs_Heaps *heaps;
  Fl_Button *wOK;
private:
  void cb_wOK_i(Fl_Button*, void*);
  static void cb_wOK(Fl_Button*, void*);
public:
  Fl_Button *wCancel;
private:
  void cb_wCancel_i(Fl_Button*, void*);
  static void cb_wCancel(Fl_Button*, void*);
public:
  Fl_Button *wApply;
private:
  void cb_wApply_i(Fl_Button*, void*);
  static void cb_wApply(Fl_Button*, void*);
public:
  int win_x, win_y, win_w, win_h; 
  Fldtk_Prefs();
  void get_prefs();
  void set_prefs();
  void update_data();
  void update_dialog();
  void set_changed();
};
#endif

//
// DyneTK, the Dyne Toolkit
// Copyright (C) 2007 Matthias Melcher
//
