//
// DyneTK, the Dyne Toolkit
// Copyright (C) 2007 Matthias Melcher
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
//

// generated by Fast Light User Interface Designer (fluid) version 1.0108

#ifndef Fldtk_Snapshot_h
#define Fldtk_Snapshot_h
#include <FL/Fl.H>
#include "allNewt.h"
#include "fltk/Flmp_Image.H"
#include <FL/Fl_RGB_Image.H>
#include <FL/Fl_File_Chooser.H>
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *snapshot;
#include <FL/Fl_Box.H>
extern Fl_Box *wImage;
#include <FL/Fl_Button.H>
void show_snapshot_window();
void update_snapshot_window(Flmp_Image *img);
#endif

//
// DyneTK, the Dyne Toolkit
// Copyright (C) 2007 Matthias Melcher
//
