// generated by Fast Light User Interface Designer (fluid) version 1.0108

#ifndef dyne_h
#define dyne_h
#include <FL/Fl.H>
#include "main.h"
#include "memory.h"
#include "asmview.h"
#include "hexview.h"
#include "registerview.h"
#include "screen.h"
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *wMain;
#include <FL/Fl_Menu_Bar.H>
extern Dn_Screen *wScreen;
extern Dn_Register_View *wRegisterView;
#include <FL/Fl_Group.H>
#include <FL/Fl_Button.H>
extern Fl_Button *wStopRun;
#include <FL/Fl_Input.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Tabs.H>
#include <FL/Fl_Tile.H>
extern Dn_Hex_View *wHexView;
extern Dn_Asm_View *wAsmView;
extern Dn_Asm_View *wTracebackView;
Fl_Double_Window* create_gui();
extern Fl_Menu_Item menu_[];
void update_gui();
extern Fl_Double_Window *wPreferences;
extern Fl_Input *wFilenameROM;
extern Fl_Button *wFilechooserROM;
extern Fl_Input *wFilenameRAM;
extern Fl_Button *wFilechooserRAM;
extern Fl_Input *wFilenameFlash;
extern Fl_Button *wFilechooserFlash;
extern Fl_Input *wFilenameSymbols;
extern Fl_Button *wFilechooserSymbols;
extern Fl_Input *wFilenameComments;
extern Fl_Button *wFilechooserComments;
extern Fl_Input *wFilenameBreakpoints;
extern Fl_Button *wFilechooserBreakpoints;
#include <FL/Fl_Check_Button.H>
extern Fl_Check_Button *wSaveRAM;
extern Fl_Check_Button *wSaveFlash;
Fl_Double_Window* create_preferences_dialog();
#endif
