// generated by Fast Light User Interface Designer (fluid) version 1.0108

#include "dmp_main.h"
Dmp_Main::Dmp_Main(int X, int Y, int W, int H, const char *L)
  : Fl_Double_Window(X, Y, W, H, L) {
  _Dmp_Main();
}

Dmp_Main::Dmp_Main(int W, int H, const char *L)
  : Fl_Double_Window(0, 0, W, H, L) {
  clear_flag(16);
  _Dmp_Main();
}

void Dmp_Main::_Dmp_Main() {
this->box(FL_FLAT_BOX);
this->color((Fl_Color)34);
this->selection_color(FL_BACKGROUND_COLOR);
this->labeltype(FL_NO_LABEL);
this->labelfont(0);
this->labelsize(14);
this->labelcolor(FL_FOREGROUND_COLOR);
this->align(FL_ALIGN_TOP);
this->when(FL_WHEN_RELEASE);
{ Fl_Group* o = new Fl_Group(10, 10, 320, 480);
  o->box(FL_FLAT_BOX);
  o->color(FL_LIGHT1);
  o->color(0xb8ca9c00);
  o->end();
} // Fl_Group* o
{ Fl_Button* o = new Fl_Button(15, 500, 60, 20, "Connect");
  o->color(FL_LIGHT1);
  o->labelfont(1);
  o->labelsize(11);
} // Fl_Button* o
{ Fl_Button* o = new Fl_Button(85, 500, 60, 20, "Reset");
  o->color(FL_LIGHT1);
  o->labelfont(1);
  o->labelsize(11);
} // Fl_Button* o
color(0x595a5000);
end();
}
