// generated by Fast Light User Interface Designer (fluid) version 1.0108

#ifndef dmp_main_h
#define dmp_main_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Button.H>

class Dmp_Main : public Fl_Double_Window {
  void _Dmp_Main();
public:
  Dmp_Main(int X, int Y, int W, int H, const char *L = 0);
  Dmp_Main(int W, int H, const char *L = 0);
};
#endif
